#!/bin/sh
# live-build auto config — Cryogram OS
set -e

lb config noauto \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --distribution bookworm \
  --archive-areas "main contrib non-free non-free-firmware" \
  --apt-recommends false \
  --apt-indices false \
  --apt-options "--yes -o APT::Get::Fix-Missing=true" \
  --debootstrap-options "--variant=minbase" \
  --bootappend-live "boot=live components quiet splash username=cryogram hostname=cryogram" \
  --iso-volume "CRYOGRAM" \
  --iso-application "Cryogram OS" \
  --memtest none \
  --debian-installer none \
  --chroot-filesystem squashfs \
  --compression xz \
  --linux-packages "linux-image linux-headers" \
  "${@}"
