---
# Cryogram OS — Calamares fstab module configuration

mountOptions:
  default:  defaults,noatime
  btrfs:    defaults,noatime,space_cache,autodefrag
  efi:      defaults,noatime,umask=0077

ssdExtraMountOptions:
  ext4:  discard
  btrfs: discard=async

ensureSuspendToDisk: false
ensureCryptoLibs: false
